import { z } from 'zod';
import { database } from '@/lib/storage';
import { card,dailyBoard,isSet,puzzleDay,replaceMatched,setKey,type Card } from '@/lib/set';
export const dynamic='force-dynamic';
const triple=z.tuple([z.number().int().min(0).max(80),z.number().int().min(0).max(80),z.number().int().min(0).max(80)]);
const bodySchema=z.discriminatedUnion('action',[z.object({action:z.literal('create'),name:z.string().trim().min(1).max(70),classes:z.array(z.string().trim().min(1).max(40)).min(1).max(20)}),z.object({action:z.literal('start'),code:z.string().regex(/^[A-Z2-9]{6}$/),className:z.string().min(1).max(40),target:z.union([z.literal(3),z.literal(6)])}),z.object({action:z.literal('claim'),id:z.string().uuid(),step:z.number().int().min(0).max(5),ids:triple}),z.object({action:z.literal('refresh'),id:z.string().uuid(),requestId:z.string().uuid()})]);
const response=(value:unknown,status=200)=>Response.json(value,{status,headers:{'Cache-Control':'no-store'}});
type State={board:Card[];sets:number[][];positions?:number[][];refreshIds?:string[]};
type Attempt={id:string;day:string;target:number;started_at:number;state:string|null;elapsed_ms:number|null;finished_at:number|null};
const codeValue=(v:unknown)=>typeof v==='string'&&/^[A-Z2-9]{6}$/.test(v)?v:null;
function result(attempt:Attempt,state:State){return {board:state.board,sets:state.sets,positions:state.positions||[],step:state.sets.length,elapsedMs:attempt.elapsed_ms,finishedAt:attempt.finished_at,saved:attempt.elapsed_ms!==null};}
async function roomData(code:string){const db=database();const room=await db.prepare('SELECT code,name,classes FROM rooms WHERE code=?').bind(code).first<{code:string;name:string;classes:string}>();if(!room)return null;const scores=await db.prepare('SELECT id,class_name AS className,day,target,elapsed_ms AS elapsedMs,finished_at AS finishedAt FROM attempts WHERE room_code=? AND elapsed_ms IS NOT NULL ORDER BY finished_at DESC LIMIT 2000').bind(code).all();return {...room,classes:JSON.parse(room.classes),scores:scores.results};}
export async function GET(request:Request){try{const url=new URL(request.url);const raw=url.searchParams.get('room');if(!raw)return response({day:puzzleDay()});const code=codeValue(raw);if(!code)return response({error:'Enter a valid six-character room code.'},400);const room=await roomData(code);return room?response(room):response({error:'That room was not found. Check the code.'},404);}catch(error){console.error('SET load',error);return response({error:'The scoreboard is unavailable. Please try again.'},503);}}
export async function POST(request:Request){try{const origin=request.headers.get('Origin');if(origin&&origin!==new URL(request.url).origin)return response({error:'Use the game page to submit results.'},403);if(Number(request.headers.get('content-length')||0)>10000)return response({error:'Request too large.'},413);let body:unknown;try{body=await request.json();}catch{return response({error:'Send a valid game request.'},400);}const parsed=bodySchema.safeParse(body);if(!parsed.success)return response({error:'Check the room details, class, and round before trying again.'},400);const input=parsed.data,db=database();
if(input.action==='create'){const name=input.name,classes=[...new Set(input.classes)];const alphabet='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';for(let retry=0;retry<5;retry++){const code=Array.from(crypto.getRandomValues(new Uint8Array(6)),n=>alphabet[n%alphabet.length]).join('');const inserted=await db.prepare('INSERT OR IGNORE INTO rooms(code,name,classes,created_at) VALUES(?,?,?,?)').bind(code,name,JSON.stringify(classes),Date.now()).run();if(inserted.meta.changes)return response({code,name,classes,scores:[]});}return response({error:'Could not create the room. Try again.'},503);}
if(input.action==='start'){const room=await db.prepare('SELECT classes FROM rooms WHERE code=?').bind(input.code).first<{classes:string}>();if(!room||!JSON.parse(room.classes).includes(input.className))return response({error:'Select one of this room’s classes.'},400);const id=crypto.randomUUID(),day=puzzleDay(),startedAt=Date.now(),board=dailyBoard(day),state=JSON.stringify({board,sets:[]});await db.prepare('INSERT INTO attempts(id,room_code,class_name,day,target,started_at,state) VALUES(?,?,?,?,?,?,?)').bind(id,input.code,input.className,day,input.target,startedAt,state).run();return response({id,board,day,startedAt,step:0});}
const attempt=await db.prepare('SELECT * FROM attempts WHERE id=?').bind(input.id).first<Attempt>();if(!attempt||!attempt.state)return response({error:'This round is no longer available. Start a new round.'},404);const state:State=JSON.parse(attempt.state),current=state.sets.length;
if(input.action==='refresh'){if(attempt.elapsed_ms!==null)return response({error:'This round is complete. Start another round to play again.'},400);if(Date.now()-attempt.started_at>86400000)return response({error:'This round has expired. Start another round.'},400);const refreshIds=state.refreshIds||[];if(refreshIds.includes(input.requestId))return response(result(attempt,state));const board=dailyBoard(`${attempt.day}:refresh:${refreshIds.length+1}:${state.board.map(c=>c.id).join(',')}`),next={...state,board,refreshIds:[...refreshIds,input.requestId]};if(refreshIds.length>=100)return response({error:'Refresh limit reached for this round. You can still find sets on this board.'},400);const updated=await db.prepare('UPDATE attempts SET state=? WHERE id=? AND state=? AND elapsed_ms IS NULL').bind(JSON.stringify(next),attempt.id,attempt.state).run();if(!updated.meta.changes)return response({error:'The board just changed. Retry once to sync it.'},409);return response(result(attempt,next));}

if(input.step<current){if(setKey(state.sets[input.step])!==setKey(input.ids))return response({error:'That board has already changed. Retry the current match.'},409);return response(result(attempt,state));}
if(input.step!==current||attempt.elapsed_ms!==null)return response({error:'The board changed. Retry the current match.'},409);
if(Date.now()-attempt.started_at>86400000)return response({error:'This round has expired. Start a new round.'},400);
if(!input.ids.every(id=>state.board.some(c=>c.id===id))||!isSet(input.ids.map(card)))return response({error:'Choose three different cards that form a set on the current board.'},400);
const sets=[...state.sets,input.ids],complete=sets.length===attempt.target,board=complete?state.board:replaceMatched(state.board,input.ids,`${attempt.day}:${current}`),nextState=JSON.stringify({...state,board,sets,positions:[...(state.positions||[]),input.ids.map(id=>state.board.findIndex(c=>c.id===id)+1).sort((a,b)=>a-b)]}),finishedAt=complete?Date.now():null,elapsedMs=finishedAt===null?null:finishedAt-attempt.started_at;
const updated=await db.prepare('UPDATE attempts SET state=?,finished_at=?,elapsed_ms=?,answers=? WHERE id=? AND state=? AND elapsed_ms IS NULL').bind(nextState,finishedAt,elapsedMs,JSON.stringify(sets),attempt.id,attempt.state).run();if(!updated.meta.changes)return response({error:'A match was just saved. Retry once to sync your board.'},409);
return response(result({...attempt,state:nextState,elapsed_ms:elapsedMs,finished_at:finishedAt},JSON.parse(nextState)));
}catch(error){console.error('SET write',error);return response({error:'Could not save this match. Your selected cards are still here; retry to continue.'},503);}}
